##################mysql??##################
chen.mysql.ip=localhost
chen.mysql.port=3306
chen.mysql.db=chen
chen.mysql.username=root
chen.mysql.password=1234
##################redis??##################
chen.redis.host=127.0.0.1
chen.redis.port=6379
chen.redis.password=1234
##################jwt##################
chen.jwt.secret=dsfsdfsdfsdfsd
##################???????##################
chen.wx.callback=http://127.0.0.1/9000
chen.wx.appId=wx1a062cd828ab7065
chen.wx.secret=ecc7505f41bb4c333e83e90a4b3d20f7
# ??????Token?
chen.wx.token=dssdfsdfs
# ??????EncodingAESKey?
chen.wx.aesKey=sha1
##################OSS配置##################
oss.enabled=true
oss.type=minio
oss.endpoint=http://127.0.0.1:9000
oss.access-key=UhEtnlxe4ShIJCnr
oss.secret-key=DdDVZjgsceuGTsFRlQPmujw8lJSqsT8s
oss.bucketName=default
##################rocketmq##################
rocketmq.name-server=127.0.0.1:9876
rocketmq.access-key=chen
rocketmq.secret-key=123456
##################gpt??##################
chen.chatgpt.use=false
chen.chatgpt.uid=10001
chen.chatgpt.key=sk-wvWM0xGcxFfsddfsgxixbXK5tHovM
chen.chatgpt.proxyUrl=https://123.cc
chen.chatglm2.use=false
chen.chatglm2.url=http://v32134.cc
chen.chatglm2.uid=10002
