################## mysql ##################
chen.mysql.ip=127.0.0.1
chen.mysql.port=3306
chen.mysql.db=chenchat
chen.mysql.username=
chen.mysql.password=

################## redis ##################
chen.redis.host=127.0.0.1
chen.redis.port=6379
chen.redis.password=

################## WX ##################
chen.wx.callback=http://127.0.0.1:8080
chen.wx.appId=
chen.wx.secret=
chen.wx.token=dssdfsdfs
chen.wx.aesKey=sha1

################## jwt ##################
chen.jwt.secret=dsadsaddddddasas

################## rocketmq ##################
chen.rocketmq.name-server=127.0.0.1:9876
chen.rocketmq.access-key=chenchat
chen.rocketmq.secret-key=

################## minio OSS ##################
oss.enabled=true
oss.type=minio
oss.endpoint=http://127.0.0.1:9000
oss.access-key=
oss.secret-key=
oss.bucketName=chenchat

################## DeepSeek AI ##################
chen.deepseek.use=true
chen.deepseek.uid=10001
chen.deepseek.key=
chen.deepseek.apiUrl=

################## Qwen AI ##################
chen.qwen.use=true
chen.qwen.uid=10002
chen.qwen.key=
chen.qwen.apiUrl=

