##################mysql配置##################
chen.mysql.ip=127.0.0.1
chen.mysql.port=3306
chen.mysql.db=chen
chen.mysql.username=1234
chen.mysql.password=1234
##################redis配置##################
chen.redis.host=127.0.0.1
chen.redis.port=6379
chen.redis.password=123456
##################jwt##################
chen.jwt.secret=dsadsaddddddasas
##################微信公众号信息##################
chen.wx.callback=http://127.0.0.1:8080
chen.wx.appId=appid
chen.wx.secret=380bfc1c9147fdsf4sf07
# 接口配置里的Token值
chen.wx.token=sdfsf
# 接口配置里的EncodingAESKey值
chen.wx.aesKey=sha1
##################OSS配置##################
oss.enabled=true
oss.type=minio
oss.endpoint=http://127.0.0.1:9000
oss.access-key=UhEtnlxe4ShIJCnr
oss.secret-key=DdDVZjgsceuGTsFRlQPmujw8lJSqsT8s
oss.bucketName=default
##################rocketmq##################
rocketmq.name-server=127.0.0.1:9876
rocketmq.access-key=root
rocketmq.secret-key=123456
##################gpt配置##################
chen.chatgpt.use=false
chen.chatgpt.uid=10001
chen.chatgpt.key=sk-wvWM0xGcxFfsddfsgxixbXK5tHovM
chen.chatgpt.proxyUrl=https://123.cc
chen.chatglm2.use=false
chen.chatglm2.url=http://v32134.cc
chen.chatglm2.uid=10002
chen.chatglm2.context=3
